Merge in new changes to i3lock
Raymo111/i3lock-color pull request #120
Opened 2019-05-25 21:17 UTC by mortie

I haven't tested everything here extensively, but reading through the code, it all seems correct enough. Basic functionality works, and the example script still does what it's supposed to. Most of the new code is for supporting reading raw images, which I added in https://github.com/i3/i3lock/pull/226.

2019-05-30 14:10 UTC, PandorasFox requested changes
Generally looks fine; couple of minor touches and it should be fine. Thanks for the large merge!

2019-05-30 14:10 UTC, PandorasFox commented on README.md
> +We recommend you use the provided package from your distribution. Do not build
Remove this paragraph, as i3lock-color doesn't generally have packages available from distros.

2019-05-30 14:10 UTC, PandorasFox commented on i3lock.c
> +                                   " [-i image.png] [-t] [-e] [-f] [-l]\n"
I don't see the case for `l` - I think that the tty lock switching isn't being checked.

2019-05-30 16:14 UTC, mortie commented
Those two things should be fixed now.

2019-05-31 00:39 UTC, merged

2019-05-31 00:40 UTC, PandorasFox commented
Thanks! I haven't had the time to sit down and do this myself; big thanks for helping keep this from falling behind :)

2019-05-31 07:25 UTC, mortie commented
No problem :)

One thing though; `load_image` takes two arguments now, the `image_path` and `image_raw_format`; when you resolved the conflict with my other PR, `load_image` ended up being called with only one argument.

I'm sorry that I ended up submitting two conflicting PRs, I don't know if there'd be a better way to do it. I felt that it was cleaner to have the two things (merging in upstream as faithfully as possible, change an i3lock-color-specific behavior) as separate PRs, but maybe that wasn't the best idea considering they touch some of the same code.

2019-05-31 19:33 UTC, PandorasFox commented
Two merges was totally alright! The merge issue is on me for thinking I could handle a merge conflict from my phone - I should have looked a bit more closely.